version: "3.4"
services:
  api:
    container_name: ks-matter-poc-api
    image: node:10.19.0
    depends_on:
      - mysql
  mysql:
    container_name: ks-matter-poc-database
    image: "mysql:5.7.20"
    restart: always
